apiVersion: v1
kind: Pod
metadata:
  name: node-sample-cqlsj
  namespace: kube-mock-system
spec:
  containers:
    - command:
        - /app/virtual-kubelet
        - --nodename
        - node-sample
        - --cpu
        - "128"
        - --memory
        - 1000Gi
        - --pods
        - "500"
        - --startup-timeout
        - 10s
        - --status-updates-interval
        - 5s
        - --log-level
        - debug
        - --klog.v
        - "2"
      env:
        - name: VKUBELET_POD_IP
          value: 192.168.1.1
        - name: KUBELET_PORT
          value: "500"
        - name: KUBECONFIG
          value: /app/conf/config
      image: zhiziuqu/kube-mock-node:v1alpha1
      imagePullPolicy: Always
      name: kube-mock
      volumeMounts:
        - mountPath: /app/conf/config
          name: volume-kubeconfig
          subPath: config
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
  volumes:
    - name: volume-kubeconfig
      secret:
        defaultMode: 420
        items:
          - key: config
            path: config
        secretName: kube-mock-node